import test from 'node:test';
import assert from 'node:assert/strict';
import {square,validateBoundary} from '../dist/boundary.mjs';
import {createRectangularCarrier,deriveCarrier,densityRetains,carrierInputFingerprint} from '../dist/carrier.mjs';
import {createWorkspace,saveCarrierStudy,restoreCarrierStudy,normalizeWorkspace,serializeWorkspace,parseBackup} from '../dist/document.mjs';
import {LocalStore,STORE_KEY,SCHEMA2_RECOVERY_KEY} from '../dist/storage.mjs';

const carrier=()=>createRectangularCarrier('carrier-fixed');
test('default 500 square yields nine clipped paths in each perpendicular family',()=>{const d=deriveCarrier(square(500),carrier(),'board');assert.deepEqual(d.diagnostics.counts.A,{retained:9,available:9,candidates:11});assert.deepEqual(d.diagnostics.counts.B,{retained:9,available:9,candidates:11});assert.equal(d.paths.filter(p=>p.family==='A').every(p=>p.direction.y===0),true);assert.equal(d.paths.filter(p=>p.family==='B').every(p=>Math.abs(p.direction.x)===0),true);});
test('rotation and independent controls move geometry without replacing identities',()=>{const c=carrier(),base=deriveCarrier(square(),c,'board');c.angleDegrees=90;c.families.A.offset=10;c.families.B.spacing=100;const moved=deriveCarrier(square(),c,'board');assert.equal(moved.diagnostics.counts.A.available,10);assert.equal(moved.diagnostics.counts.B.available,5);assert.equal(base.paths.find(p=>p.family==='A'&&p.k===0).id,moved.paths.find(p=>p.family==='A'&&p.k===0).id);assert.notEqual(base.inputFingerprint,moved.inputFingerprint);});
test('negative indexes use deterministic nested density selection',()=>{for(let density=1;density<100;density++){const low=[...Array(201)].map((_,i)=>i-100).filter(k=>densityRetains(k,density));const high=[...Array(201)].map((_,i)=>i-100).filter(k=>densityRetains(k,density+1));assert.equal(low.every(k=>high.includes(k)),true);}assert.equal([...Array(100)].map((_,i)=>i-50).filter(k=>densityRetains(k,37)).length,37);});
test('concave U boundary produces separated fragments with no notch bridge',()=>{const u=validateBoundary([{x:-150,y:-150},{x:150,y:-150},{x:150,y:150},{x:50,y:150},{x:50,y:-50},{x:-50,y:-50},{x:-50,y:150},{x:-150,y:150}]),c=carrier();c.families.A.spacing=100;c.families.B.spacing=100;const d=deriveCarrier(u,c,'board'),top=d.paths.find(p=>p.family==='A'&&p.k===1);assert.equal(top.intervals.length,2);assert.equal(top.intervals[0].end.x,-50);assert.equal(top.intervals[1].start.x,50);});
test('winding does not affect clipping and tangency/collinear boundary paths are excluded',()=>{const boundary=square(),cw={...boundary,points:[...boundary.points].reverse()},a=deriveCarrier(boundary,carrier(),'board'),b=deriveCarrier(cw,carrier(),'board');assert.deepEqual(a.diagnostics.counts,b.diagnostics.counts);assert.equal(a.paths.some(p=>Math.abs(p.k)===5),false);assert.equal(a.diagnostics.contacts.some(c=>c.type==='collinear-overlap'),true);});
test('fingerprint excludes metadata but scopes fragments to geometry revisions',()=>{const b=square(),c=carrier(),f1=carrierInputFingerprint({...b,source:{filename:'one.svg',format:'svg',axisConversion:'negate-y'}},c),f2=carrierInputFingerprint({...b,source:{filename:'two.svg',format:'svg',axisConversion:'negate-y'}},c);assert.equal(f1,f2);const moved=structuredClone(b);moved.points[0].x+=1;assert.notEqual(f1,carrierInputFingerprint(moved,c));assert.notEqual(deriveCarrier(b,c,'board').paths[0].intervals[0].fragmentKey,deriveCarrier(moved,c,'board').paths[0].intervals[0].fragmentKey);});
test('carrier limits reject before producing a partial model',()=>{const c=carrier();c.families.A.spacing=.01;c.families.B.spacing=.01;assert.throws(()=>deriveCarrier(square(),c,'board'),/2,000 source-line limit/);});
test('carrier studies are immutable named revisions and restore boundary plus recipe atomically',()=>{let p=createWorkspace().projects[0];p.working.carrier=carrier();const first=saveCarrierStudy(p,'study');p=first.project;const old=structuredClone(p.carrierStudies[0].revisions[0]);p.working.boundary=square(300);p.working.carrier.families.A.spacing=25;p=saveCarrierStudy(p,'study').project;assert.deepEqual(p.carrierStudies[0].revisions[0],old);assert.equal(p.carrierStudies[0].revisions.length,2);const restored=restoreCarrierStudy(p,old.id);assert.equal(restored.working.boundary.points[1].x,250);assert.equal(restored.working.carrier.families.A.spacing,50);});
test('schema 2 normalizes to current schema 4 and both backup generations import',()=>{const current=createWorkspace(),legacy=structuredClone(current);legacy.schemaVersion=2;for(const p of legacy.projects){delete p.working.carrier;delete p.working.carrierSourceRevisionId;delete p.carrierStudies;}const normalized=normalizeWorkspace(legacy);assert.equal(normalized.schemaVersion,4);assert.equal(normalized.projects[0].working.carrier,null);assert.deepEqual(normalized.projects[0].carrierStudies,[]);const backup=JSON.parse(serializeWorkspace(current));backup.workspace=legacy;assert.equal(parseBackup(JSON.stringify(backup)).schemaVersion,4);});
test('first current-schema write preserves exact schema 2 JSON and aborts if recovery backup fails',()=>{const modern=createWorkspace(),legacy=structuredClone(modern);legacy.schemaVersion=2;for(const p of legacy.projects){delete p.working.carrier;delete p.working.carrierSourceRevisionId;delete p.carrierStudies;}const raw=JSON.stringify(legacy),map=new Map([[STORE_KEY,raw]]),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};const store=new LocalStore(storage),loaded=store.load();store.save(loaded);assert.equal(map.get(SCHEMA2_RECOVERY_KEY),raw);assert.equal(JSON.parse(map.get(STORE_KEY)).schemaVersion,4);const map2=new Map([[STORE_KEY,raw]]),blocked={getItem:k=>map2.get(k)??null,setItem:(k,v)=>{if(k===SCHEMA2_RECOVERY_KEY)throw new Error('quota');map2.set(k,v);}},store2=new LocalStore(blocked),loaded2=store2.load();assert.throws(()=>store2.save(loaded2),/unavailable or full/);assert.equal(map2.get(STORE_KEY),raw);});
test('representative carrier derivation stays within the recorded performance target',()=>{const pts=[];for(let i=0;i<100;i++){const a=2*Math.PI*i/100,r=i%2?250:220;pts.push({x:r*Math.cos(a),y:r*Math.sin(a)});}const boundary=validateBoundary(pts),c=carrier();c.families.A.spacing=2.5;c.families.B.spacing=2.5;for(let i=0;i<3;i++)deriveCarrier(boundary,c,'perf');const samples=[];for(let i=0;i<30;i++){const start=performance.now();deriveCarrier(boundary,c,'perf');samples.push(performance.now()-start);}samples.sort((a,b)=>a-b);assert.ok(samples[Math.floor(samples.length*.95)]<=100,`p95 ${samples[Math.floor(samples.length*.95)]}ms`);});
