import test from 'node:test';import assert from 'node:assert/strict';
import {createWorkspace,saveCarrierStudy,createWeaveStudy,addInfluence,clone} from '../dist/document.mjs';
import {createRectangularCarrier} from '../dist/carrier.mjs';
import {deriveCombinedAsync} from '../dist/combined.mjs';
import {COMBINED_VERSIONS} from '../dist/combined.mjs';import {dependencyPlan} from '../dist/dependency-plan.mjs';import {digest} from '../dist/weave.mjs';import {Worker} from 'node:worker_threads';import {once} from 'node:events';

function setup(){const w=createWorkspace(),p=w.projects[0];p.working.carrier=createRectangularCarrier('incremental');w.projects[0]=saveCarrierStudy(p,'SOURCE').project;w.projects[0]=createWeaveStudy(w.projects[0],w.projects[0].carrierStudies[0].latestRevisionId);w.projects[0]=addInfluence(w.projects[0],'attractor');return w.projects[0];}
const derive=(p,g,incremental)=>deriveCombinedAsync(p.working.boundary,p.working.carrier,p.id,p.working.weave.sourceContext,g,incremental);
test('single-family incremental derivation is byte-for-byte equal to a full derivation',async()=>{const p=setup(),base=clone(p.working.weave.generation),f=base.influences[0];f.families.A.strength=90;f.families.B.strength=10;const previous=await derive(p,base),next=clone(base);next.influences[0].families.B.strength=20;const full=await derive(p,next),incremental=await derive(p,next,{previous,families:['B']});assert.deepEqual(incremental,full);assert.ok(incremental.__familyWork.A);assert.ok(incremental.__familyWork.B);assert.equal(Object.keys(incremental).includes('__familyWork'),false);});
test('persistent worker rebuilds only the affected family and returns the full exact result',async()=>{const p=setup(),base=clone(p.working.weave.generation);base.influences[0].families.A.strength=90;base.influences[0].families.B.strength=10;const next=clone(base);next.influences[0].families.B.strength=20;const worker=new Worker(new URL('../scripts/r1b-worker-node.mjs',import.meta.url));try{let previousCandidate;for(const [index,generation] of [base,next].entries()){const candidate={boundary:p.working.boundary,carrier:p.working.carrier,sourceContext:p.working.weave.sourceContext,generation},plan=dependencyPlan(previousCandidate,candidate),response=once(worker,'message');worker.postMessage({protocolVersion:COMBINED_VERSIONS.protocol,workerBuildId:'phase4-test',sessionId:'test',requestSequence:index+1,requestId:'incremental:'+(index+1),boardId:p.id,weaveStudyId:p.working.weave.studyId,baseCommittedFingerprint:'root',candidateInputFingerprint:digest(candidate),algorithmVersions:COMBINED_VERSIONS,dependencyPlan:plan,candidate});const [message]=await response;assert.equal(message.type,'success',message.error?.message);if(index===1){assert.deepEqual(message.reused,['family:A']);assert.deepEqual(message.result,await derive(p,next));}previousCandidate=candidate;}}finally{await worker.terminate();}});
