import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,saveBoundary,saveCarrierStudy,createWeaveStudy,saveWeaveStudy,addWeaveFamily,removeWeaveFamily,validateTrustedWorkspace} from '../dist/document.mjs';
import {createRectangularCarrier,familyNames} from '../dist/carrier.mjs';
import {effectiveFamilyCatalog,updateFamilyCatalog,indexDerivedFamilies,indexCrossingFamilies} from '../dist/family-domain.mjs';
import {canonical} from '../dist/weave.mjs';
import {packWorkspace,portableText,parsePortable} from '../dist/storage-codec.mjs';
const carrierInputFingerprint=carrier=>canonical(carrier);

function study(){const ws=createWorkspace();let p=ws.projects[0];p=saveBoundary(p,'BOUNDARY').project;p.working.carrier=createRectangularCarrier('carrier-family-test');p=saveCarrierStudy(p,'PATTERN').project;p=createWeaveStudy(p,p.carrierStudies[0].latestRevisionId);p=saveWeaveStudy(p,'FIELD',true).project;ws.projects[0]=p;return {ws,p};}

test('legacy family identities are deterministic and explicit catalogs persist through immutable backup',()=>{let {ws,p}=study();const legacy=effectiveFamilyCatalog(p.working.carrier,undefined),again=effectiveFamilyCatalog(p.working.carrier,undefined);assert.deepEqual(legacy,again);assert.equal(new Set(legacy.entries.map(x=>x.id)).size,2);assert.ok(p.working.familyCatalog);validateTrustedWorkspace(ws);assert.deepEqual(parsePortable(portableText(packWorkspace(ws))),ws);});

test('family labels, order and export settings do not alter certified geometry or compact payload bytes',()=>{const setup=study(),ws=setup.ws;let p=setup.p;const beforeGeometry=canonical(p.working.weave.derived),beforeFingerprint=carrierInputFingerprint(p.working.carrier),before=packWorkspace(ws),a=p.working.familyCatalog.entries.find(x=>x.key==='A');p.working.familyCatalog=updateFamilyCatalog(p.working.carrier,p.working.familyCatalog,'A',{label:'WARP',includeInExport:false,move:1});p=saveWeaveStudy(p,'FIELD',true).project;ws.projects[0]=p;const after=packWorkspace(ws);assert.equal(canonical(p.working.weave.derived),beforeGeometry);assert.equal(carrierInputFingerprint(p.working.carrier),beforeFingerprint);assert.equal(after.payloads[0].id,before.payloads[0].id);assert.deepEqual([...new Uint8Array(after.payloads[0].f64)],[...new Uint8Array(before.payloads[0].f64)]);assert.equal(p.working.familyCatalog.entries.find(x=>x.id===a.id).label,'WARP');assert.equal(p.working.familyCatalog.entries.find(x=>x.id===a.id).includeInExport,false);assert.deepEqual(p.working.familyCatalog.entries.sort((x,y)=>x.order-y.order).map(x=>x.key),['B','A']);});

test('deleting a family preserves every surviving engine key and permanent identity',()=>{let {p}=study();let added=addWeaveFamily(p);p=added.project;const cId=p.working.familyCatalog.entries.find(x=>x.key==='C').id;added=addWeaveFamily(p);p=added.project;const dId=p.working.familyCatalog.entries.find(x=>x.key==='D').id;p=removeWeaveFamily(p,'B');assert.deepEqual(familyNames(p.working.carrier),['A','C','D']);assert.equal(p.working.familyCatalog.entries.find(x=>x.key==='C').id,cId);assert.equal(p.working.familyCatalog.entries.find(x=>x.key==='D').id,dId);const next=addWeaveFamily(p);assert.equal(next.family,'B');assert.notEqual(next.project.working.familyCatalog.entries.find(x=>x.key==='B').id,cId);assert.deepEqual(familyNames(next.project.working.carrier),['A','B','C','D']);});

test('derived and crossing indexes reference stable family identities without copying geometry',()=>{const {p}=study(),index=indexDerivedFamilies(p.working),ids=new Map(index.families.map(x=>[x.key,x.id]));assert.equal(index.provenanceFingerprint,p.working.weave.derived.provenanceFingerprint);assert.equal(index.families.reduce((n,x)=>n+x.strandCount,0),p.working.weave.derived.strands.length);const refs=indexCrossingFamilies(p.working,{events:[{id:'x',a:{si:0},b:{si:p.working.weave.derived.strands.findIndex(s=>s.family==='B')}}]});assert.deepEqual(refs[0].familyIds,[ids.get('A'),ids.get('B')]);assert.strictEqual(p.working.weave.derived.strands[index.families[0].strandIndexes[0]],p.working.weave.derived.strands[index.families[0].strandIndexes[0]]);});

test('compact codec accepts nonconsecutive family keys after deletion',()=>{let {ws,p}=study();p=addWeaveFamily(p).project;p=removeWeaveFamily(p,'B');p=saveCarrierStudy(p,'PATTERN').project;p=createWeaveStudy(p,p.carrierStudies[0].latestRevisionId);p=saveWeaveStudy(p,'FIELD 2',true).project;ws.projects[0]=p;const restored=parsePortable(portableText(packWorkspace(ws)));assert.deepEqual(familyNames(restored.projects[0].working.carrier),['A','C']);assert.deepEqual(restored.projects[0].working.familyCatalog,p.working.familyCatalog);});
