import test from 'node:test';
import assert from 'node:assert/strict';
import {FIELD_PRESENTATION_DEFAULT,validateFieldPresentation,effectiveFieldPresentation,changeFieldPresentation,presentationTailStrands,presentationTailLayers,presentationWovenStrands,presentationTrace,presentationBleedStrands} from '../dist/field-presentation.mjs';
import {findCrossings,defaultInterlacing} from '../dist/interlacing.mjs';
import {continuousWeaveSvg} from '../dist/weave-occlusion.mjs';
import {createWorkspace,saveBoundary,saveCarrierStudy,createWeaveStudy,saveWeaveStudy,restoreWeaveStudy,validateTrustedWorkspace} from '../dist/document.mjs';
import {createLinePreset} from '../dist/line-presets.mjs';
import {packWorkspace,portableText,parsePortable,prepareIncrementalRevisionWorkspace} from '../dist/storage-codec.mjs';
import {digest,derivedSvg} from '../dist/weave.mjs';

const boundary={points:[{x:-10,y:-10},{x:10,y:-10},{x:10,y:10},{x:-10,y:10}]};
const strands=[{family:'A',strandId:'a',direction:{x:1,y:0},fragments:[{fragmentId:'edge',points:[{x:-10,y:0},{x:10,y:0}]},{fragmentId:'inside',points:[{x:-5,y:2},{x:5,y:2}]}]}];

test('field presentation validates bounded durable decisions and materializes defaults',()=>{assert.deepEqual(effectiveFieldPresentation(),FIELD_PRESENTATION_DEFAULT);for(const patch of [{mode:'bad'},{recoveryLength:.41},{endVariation:-.01},{relaxation:2},{boundaryEmphasis:'strong'}])assert.throws(()=>changeFieldPresentation(undefined,patch),/Invalid weave field presentation/);const value=changeFieldPresentation(undefined,{mode:'loose',recoveryLength:.3,endVariation:.4,relaxation:.75,boundaryEmphasis:'reference'});assert.doesNotThrow(()=>validateFieldPresentation(value));});

test('recovery is deterministic, continuous, family-directed and leaves certified strands untouched',()=>{const copy=structuredClone(strands),settings=changeFieldPresentation(undefined,{endVariation:.3}),first=presentationTailStrands(strands,boundary,settings),second=presentationTailStrands(strands,boundary,settings);assert.deepEqual(first,second);assert.deepEqual(strands,copy);assert.equal(first[0].fragments.length,2);for(const fragment of first[0].fragments){assert.deepEqual(fragment.points[0],fragment.presentationEnd==='start'?strands[0].fragments[0].points[0]:strands[0].fragments[0].points.at(-1));assert.equal(fragment.points.length,9);const last=fragment.points.at(-1);assert.ok(Math.abs(last.y)<1e-9);assert.ok(Math.abs(last.x)>10);}assert.deepEqual(presentationTailStrands(strands,boundary,changeFieldPresentation(undefined,{mode:'crop'})),[]);});

test('recovery follows certified contacts on irregular boundaries without assuming a square mask',()=>{const irregular={points:[{x:-12,y:-8},{x:8,y:-8},{x:13,y:2},{x:4,y:11},{x:-10,y:7}]},source=[{family:'B',strandId:'irregular',direction:{x:2,y:1},fragments:[{fragmentId:'sloped-edge',points:[{x:8,y:-8},{x:10,y:-4}]}]}],tails=presentationTailStrands(source,irregular);assert.equal(tails.length,1);assert.equal(tails[0].fragments.length,2);for(const fragment of tails[0].fragments){assert.equal(fragment.points.length,9);assert.ok(fragment.points.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));const original=fragment.presentationEnd==='start'?source[0].fragments[0].points[0]:source[0].fragments[0].points.at(-1);assert.deepEqual(fragment.points[0],original);assert.notDeepEqual(fragment.points.at(-1),original);}});

test('loose, fray and bleed presentations keep open paths and only extend touching ends',()=>{const loose=presentationTailStrands(strands,boundary,changeFieldPresentation(undefined,{mode:'loose'})),fray=presentationTailLayers(strands,boundary,changeFieldPresentation(undefined,{mode:'fray'})),bleed=presentationBleedStrands(strands,boundary);assert.equal(fray.length,2);assert.equal(fray[0].opacity,.72);assert.equal(fray[1].opacity,.28);assert.ok(Math.abs(loose[0].fragments[0].points.at(-1).x)>Math.abs(presentationTailStrands(strands,boundary)[0].fragments[0].points.at(-1).x));assert.equal(bleed[0].fragments[0].points.length,18);assert.deepEqual(bleed[0].fragments[1].points,strands[0].fragments[1].points);});

test('recovery-zone crossings retain active over-under masks and open contours',()=>{const source=[{family:'A',strandId:'a',k:0,direction:{x:1,y:1},fragments:[{fragmentId:'a-edge',points:[{x:0,y:-4},{x:10,y:-2}]}]},{family:'B',strandId:'b',k:0,direction:{x:1,y:-1},fragments:[{fragmentId:'b-edge',points:[{x:0,y:4},{x:10,y:2}]}]}],tails=presentationWovenStrands(source,boundary),result=findCrossings(tails,presentationTrace(tails)),settings={...defaultInterlacing(),enabled:true,topFamily:'A'},svg=continuousWeaveSvg(tails,result,settings,undefined,'source',boundary,{idPrefix:'recovery-occlusion-',presentation:true});assert.equal(result.counts.crossings,1);assert.match(svg,/mask="url\(#recovery-occlusion-/);assert.equal((svg.match(/data-boundary-continuation="true"/g)||[]).length,2);for(const path of svg.match(/<path data-weave-family[^>]+>/g))assert.doesNotMatch(path,/\bZ\b/);});

test('field presentation saves, reloads and exports without changing certified geometry payloads',()=>{const ws=createWorkspace();let p=ws.projects[0];p=saveBoundary(p,'B').project;p.working.carrier=createLinePreset('square-grid','field-presentation');p.working.fieldPresentation=changeFieldPresentation(undefined,{mode:'fray',recoveryLength:.28,endVariation:.35,relaxation:.8,boundaryEmphasis:'hidden'});const pattern=saveCarrierStudy(p,'P');p=createWeaveStudy(pattern.project,pattern.revisionId);p=saveWeaveStudy(p,'W',true).project;ws.projects[0]=p;const before=packWorkspace(ws),geometry=digest(p.working.weave.derived),revision=p.weaveStudies[0].latestRevisionId;p=structuredClone(p);p.working.fieldPresentation=changeFieldPresentation(p.working.fieldPresentation,{mode:'loose'});p=saveWeaveStudy(p,'W',true).project;ws.projects[0]=p;validateTrustedWorkspace(ws);const delta=prepareIncrementalRevisionWorkspace(ws,before);assert.equal(delta.newPayloads.length,0);assert.equal(digest(p.working.weave.derived),geometry);const roundtrip=parsePortable(portableText(delta.packed));assert.deepEqual(roundtrip,ws);assert.equal(restoreWeaveStudy(p,p.weaveStudies[0].latestRevisionId).working.fieldPresentation.mode,'loose');assert.equal(restoreWeaveStudy(p,revision).working.fieldPresentation.mode,'fray');const svg=derivedSvg(p.working,p.id,true);assert.match(svg,/field-presentation-v1/);assert.match(svg,/family-recovery-v1/);assert.match(svg,/data-presentation-part="recovery-0"/);assert.doesNotMatch(svg,/\bZ\b/);});

test('field presentation controls share the presentation-only save path',async()=>{const html=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../dist/index.html',import.meta.url),'utf8')),app=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../dist/app.mjs',import.meta.url),'utf8'));for(const id of ['field-edge-mode','field-recovery','field-variation','field-relaxation','field-boundary-emphasis'])assert.match(html,new RegExp('id="'+id+'"'));assert.match(app,/previewFieldPresentation/);assert.match(app,/presentation:true/);assert.match(app,/FIELD PRESENTATION SAVED\. GEOMETRY UNCHANGED/);});
