import test from 'node:test';import assert from 'node:assert/strict';import {segmentMeeting,findCrossings,wovenStrands,defaultInterlacing,validateInterlacing} from '../dist/interlacing.mjs';
const strand=(id,family,points)=>({strandId:id,family,fragments:[{t0:0,t1:1,points}]});const pair=()=>[strand('a','A',[{x:-10,y:0},{x:10,y:0}]),strand('b','B',[{x:0,y:-10},{x:0,y:10}])];
test('exact represented intersections distinguish crossings, endpoint contact and overlap',()=>{const p=pair(),a=p[0].fragments[0].points,b=p[1].fragments[0].points;assert.equal(segmentMeeting(...a,...b).type,'crossing');assert.equal(segmentMeeting(...a,{x:10,y:0},{x:10,y:5}).type,'contact');assert.equal(segmentMeeting(...a,{x:0,y:0},{x:20,y:0}).type,'overlap');assert.equal(segmentMeeting({x:0,y:0},{x:1,y:1e-15},{x:0,y:1e-15},{x:1,y:2e-15}),null);});
test('priority and input-bound reversal cut only presentation, keep fragments separate',()=>{const p=pair(),copy=structuredClone(p),r=findCrossings(p),settings={...defaultInterlacing(),enabled:true};assert.equal(r.events.length,1);let out=wovenStrands(p,r,settings,undefined,'input');assert.equal(out[0].fragments.length,1);assert.equal(out[1].fragments.length,2);settings.source='input';settings.overrides=[[r.events[0].id,false]];out=wovenStrands(p,r,settings,undefined,'input');assert.equal(out[0].fragments.length,2);assert.equal(out[1].fragments.length,1);assert.equal(wovenStrands(p,r,settings,undefined,'other')[1].fragments.length,2);assert.deepEqual(p,copy);assert.equal(findCrossings([...p].reverse()).events[0].id,r.events[0].id);});
test('multiway and endpoint meetings remain unresolved; same-family self crossings counted',()=>{const p=pair();p.push(strand('c','C',[{x:-10,y:-10},{x:10,y:10}]));const r=findCrossings(p);assert.equal(r.events.length,3);assert.ok(r.events.every(e=>e.ambiguous));const self=[strand('s','A',[{x:-1,y:-1},{x:1,y:1},{x:-1,y:1},{x:1,y:-1}])];assert.equal(findCrossings(self).events.length,1);const contact=pair();contact.push(strand('c','C',[{x:0,y:0},{x:5,y:5}]));assert.ok(findCrossings(contact).events[0].ambiguous);});
test('concave gaps cannot create crossings; invalid settings fail closed',()=>{const a=strand('a','A',[{x:-3,y:0},{x:-1,y:0}]);a.fragments.push({points:[{x:1,y:0},{x:3,y:0}],t0:2,t1:3});assert.equal(findCrossings([a,pair()[1]]).events.length,0);assert.throws(()=>validateInterlacing({...defaultInterlacing(),clearance:NaN}));assert.throws(()=>validateInterlacing({...defaultInterlacing(),overrides:[['a',true],['a',false]]}));});
import {createWorkspace,saveCarrierStudy,createWeaveStudy,saveWeaveStudy,validateTrustedWorkspace} from '../dist/document.mjs';import {createStitchSource} from '../dist/stitch-source.mjs';import {packWorkspace,portableText,parsePortable,prepareIncrementalRevisionWorkspace} from '../dist/storage-codec.mjs';import {digest,derivedSvg} from '../dist/weave.mjs';
test('rule saves reuse exact certified geometry and portable backup, SVG requires current result',()=>{const ws=createWorkspace();let p=ws.projects[0];p.working.carrier=createStitchSource('herringbone-square','test');p=saveCarrierStudy(p,'PATTERN').project;p=createWeaveStudy(p,p.carrierStudies[0].latestRevisionId);p=saveWeaveStudy(p,'WEAVE',true).project;ws.projects[0]=p;const packed=packWorkspace(ws),hash=digest(p.working.weave.derived);p.working.interlacing={...defaultInterlacing(),enabled:true,topFamily:'foundation'};p=saveWeaveStudy(p,'WEAVE',true).project;ws.projects[0]=p;validateTrustedWorkspace(ws);const next=prepareIncrementalRevisionWorkspace(ws,packed);assert.equal(next.newPayloads.length,0);assert.deepEqual(parsePortable(portableText(next.packed)),ws);assert.equal(digest(p.working.weave.derived),hash);assert.throws(()=>derivedSvg(p.working,p.id,true),/Wait/);const r=findCrossings(p.working.weave.derived.strands),out=wovenStrands(p.working.weave.derived.strands,r,p.working.interlacing,undefined,'x');assert.match(derivedSvg(p.working,p.id,true,r),/interlacing-v1/);});

test('sweep candidate enumeration matches exhaustive pair oracle and ignores list order',()=>{let seed=123;const rnd=()=>((seed=(1664525*seed+1013904223)>>>0)/4294967296)*20-10;const paths=Array.from({length:40},(_,i)=>strand(String(i).padStart(3,'0'),i%2?'A':'B',[{x:rnd(),y:rnd()},{x:rnd(),y:rnd()}]));let count=0;for(let i=0;i<paths.length;i++)for(let j=i+1;j<paths.length;j++)if(segmentMeeting(...paths[i].fragments[0].points,...paths[j].fragments[0].points)?.type==='crossing')count++;const a=findCrossings(paths),b=findCrossings([...paths].reverse());assert.equal(a.events.length,count);assert.deepEqual(a.events.map(e=>e.id).sort(),b.events.map(e=>e.id).sort());});
