import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,saveBoundary,saveBoundaryAndUpdatePatterns,saveCarrierStudy,createWeaveStudy,retargetWeaveSource,addWeaveFamily,removeWeaveFamily,addInfluence,candidateInfluence,candidateVariation,saveWeaveStudy,restoreWeaveStudy,duplicateLibraryItem,deleteLibraryItem,renameLibraryItem,validateTrustedWorkspace,clone} from '../dist/document.mjs';
import {createRectangularCarrier,deriveCarrier,familyNames} from '../dist/carrier.mjs';
import {refreshWeave,canonical} from '../dist/weave.mjs';
import {packWorkspace,unpackWorkspace} from '../dist/storage-codec.mjs';
import {signedVariation} from '../dist/combined.mjs';

function pattern(){let workspace=createWorkspace(),project=workspace.projects[0];project=saveBoundary(project,'BOUNDARY 01').project;project.working.carrier=createRectangularCarrier('pattern-fixed');project=addWeaveFamily(project).project;project=addWeaveFamily(project).project;return{workspace,project};}

test('dynamic families preserve the accepted A/B variation sequence exactly',()=>{assert.equal(signedVariation(1042,'A',-7),0.5583215885698614);assert.equal(signedVariation(1042,'A',0),-0.6494012474197431);assert.equal(signedVariation(1042,'B',-7),-0.6925553785852518);assert.equal(signedVariation(1042,'B',19),0.6045057348917484);assert.notEqual(signedVariation(1042,'C',19),signedVariation(1042,'B',19));});

test('a Weave Pattern embeds two through eight independently directed families',()=>{let {project}=pattern();assert.deepEqual(familyNames(project.working.carrier),['A','B','C','D']);project.working.carrier.families.C={angleDegrees:30,spacing:40,offset:7,density:65};project.working.carrier.families.D={angleDegrees:-30,spacing:70,offset:-9,density:80};const derived=deriveCarrier(project.working.boundary,project.working.carrier,project.id);assert.deepEqual(Object.keys(derived.diagnostics.counts),['A','B','C','D']);assert.ok(derived.paths.some(p=>p.family==='C'));assert.ok(derived.paths.some(p=>p.family==='D'));for(let i=4;i<8;i++)project=addWeaveFamily(project).project;assert.equal(familyNames(project.working.carrier).length,8);assert.throws(()=>addWeaveFamily(project),/no more than 8/);project=removeWeaveFamily(project,'H');assert.equal(familyNames(project.working.carrier).length,7);});

test('dynamic family influence response, variation, compact storage and restore remain exact',()=>{let {workspace,project}=pattern();project=saveCarrierStudy(project,'FOUR FAMILY PATTERN').project;project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);project=addInfluence(project,'deflector');const field=project.working.weave.generation.influences[0];project=candidateInfluence(project,{influenceId:field.id,family:'C',familySettings:{strength:75,tension:20}});project=candidateVariation(project,{family:'D',amount:33,seed:9182});project.working=refreshWeave(project.working,project.id);project=saveWeaveStudy(project,'INFLUENCED GRID 01',true).project;workspace.projects[0]=project;validateTrustedWorkspace(workspace);const round=unpackWorkspace(packWorkspace(workspace));assert.equal(canonical(round),canonical(workspace));assert.equal(round.projects[0].working.weave.generation.influences[0].families.C.strength,75);assert.equal(round.projects[0].working.weave.generation.variation.families.D.amount,33);});

test('nested duplication copies pattern families and influenced children with new identities',()=>{let {workspace,project}=pattern();project=saveCarrierStudy(project,'PATTERN').project;project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);project=addInfluence(project);project.working=refreshWeave(project.working,project.id);project=saveWeaveStudy(project,'GRID',true).project;const originalPattern=project.carrierStudies[0],originalGrid=project.weaveStudies[0];project=duplicateLibraryItem(project,'pattern',originalPattern.id);assert.equal(project.carrierStudies.length,2);assert.equal(project.weaveStudies.length,2);assert.notEqual(project.carrierStudies[1].revisions[0].carrier.id,originalPattern.revisions[0].carrier.id);assert.deepEqual(familyNames(project.carrierStudies[1].revisions[0].carrier),['A','B','C','D']);assert.notEqual(project.weaveStudies[1].id,originalGrid.id);assert.notEqual(project.weaveStudies[1].revisions[0].working.weave.generation.influences[0].id,originalGrid.revisions[0].working.weave.generation.influences[0].id);validateTrustedWorkspace({...workspace,projects:[project]});});

test('rename and cascading delete act on the visible saved hierarchy',()=>{let {project}=pattern();project=saveCarrierStudy(project,'PATTERN').project;project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);project=addInfluence(project);project.working=refreshWeave(project.working,project.id);project=saveWeaveStudy(project,'GRID',true).project;project=renameLibraryItem(project,'pattern',project.carrierStudies[0].id,'RENAMED PATTERN');assert.equal(project.carrierStudies[0].name,'RENAMED PATTERN');project=deleteLibraryItem(project,'pattern',project.carrierStudies[0].id);assert.equal(project.carrierStudies.length,0);assert.equal(project.weaveStudies.length,0);assert.equal(project.working.carrier,null);assert.equal(project.working.weave,null);});

test('same-name Boundary save advances one visible object and reclips attached Pattern',()=>{let {workspace,project}=pattern();project=saveCarrierStudy(project,'PATTERN').project;project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);project=addInfluence(project);project.working=refreshWeave(project.working,project.id);project=saveWeaveStudy(project,'GRID',true).project;const boundaryId=project.boundaries[0].id,patternId=project.carrierStudies[0].id,oldPatternRevision=project.carrierStudies[0].latestRevisionId;project.working.boundary={...project.working.boundary,points:project.working.boundary.points.map(p=>({x:p.x*.7,y:p.y*.7}))};const result=saveBoundaryAndUpdatePatterns(project,'BOUNDARY 01');project=result.project;assert.equal(project.boundaries.length,1);assert.equal(project.boundaries[0].id,boundaryId);assert.equal(project.boundaries[0].revisions.length,2);assert.equal(project.carrierStudies.length,1);assert.equal(project.carrierStudies[0].id,patternId);assert.equal(project.carrierStudies[0].revisions.length,2);assert.notEqual(project.carrierStudies[0].latestRevisionId,oldPatternRevision);assert.equal(project.working.carrierSourceRevisionId,project.carrierStudies[0].latestRevisionId);assert.equal(project.working.weave.sourceContext.sourceCarrierRevisionId,project.carrierStudies[0].latestRevisionId);assert.equal(project.working.weave.derived,null);project.working=refreshWeave(project.working,project.id);workspace.projects[0]=project;validateTrustedWorkspace(workspace);});

test('family edits preserve an active influence and synchronize its family settings',()=>{let {workspace,project}=pattern();project=saveCarrierStudy(project,'PATTERN').project;project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);project=addInfluence(project);const influenceId=project.working.weave.generation.influences[0].id,result=addWeaveFamily(project,'A');project=result.project;assert.equal(project.working.weave.generation.influences[0].id,influenceId);assert.ok(project.working.weave.generation.influences[0].families[result.family]);project=removeWeaveFamily(project,result.family);assert.equal(project.working.weave.generation.influences[0].id,influenceId);assert.deepEqual(Object.keys(project.working.weave.generation.influences[0].families),familyNames(project.working.carrier));project.working=refreshWeave(project.working,project.id);workspace.projects[0]=project;validateTrustedWorkspace(workspace);});

test('spacing changes after influences preserve fields and save a coherent updated result',()=>{let {workspace,project}=pattern();project=saveCarrierStudy(project,'PATTERN').project;project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);project=addInfluence(project);const fieldBefore=clone(project.working.weave.generation.influences[0]),fingerprintBefore=refreshWeave(project.working,project.id).weave.derived.contentFingerprint;project.working.carrier.families.A.spacing+=17;const savedPattern=saveCarrierStudy(project,'PATTERN');project=retargetWeaveSource(savedPattern.project,savedPattern.revisionId);assert.deepEqual(project.working.weave.generation.influences[0],fieldBefore);project.working=refreshWeave(project.working,project.id);assert.notEqual(project.working.weave.derived.contentFingerprint,fingerprintBefore);project=saveWeaveStudy(project,'GRID',true).project;workspace.projects[0]=project;validateTrustedWorkspace(workspace);const round=unpackWorkspace(packWorkspace(workspace)),restored=restoreWeaveStudy(round.projects[0],round.projects[0].weaveStudies[0].latestRevisionId);assert.equal(restored.working.carrier.families.A.spacing,project.working.carrier.families.A.spacing);assert.deepEqual(restored.working.weave.generation.influences[0],fieldBefore);assert.equal(restored.working.weave.derived.contentFingerprint,project.working.weave.derived.contentFingerprint);});
import {recoverCarrierAncestry} from '../dist/ancestry-recovery.mjs';
import {prepareIncrementalWorkspace,encodeDerived} from '../dist/storage-codec.mjs';
test('incremental field commits persist pattern ancestry and saved field revisions together',()=>{
 let {workspace,project}=pattern();project=saveCarrierStudy(project,'PATTERN').project;project=createWeaveStudy(project,project.working.carrierSourceRevisionId);project=addInfluence(project);project.working=refreshWeave(project.working,project.id);workspace.projects[0]=project;const base=packWorkspace(workspace);
 project.working.carrier.families.A.spacing+=10;const saved=saveCarrierStudy(project,'PATTERN');project=retargetWeaveSource(saved.project,saved.revisionId);project.working=refreshWeave(project.working,project.id);project=saveWeaveStudy(project,'GRID',true).project;workspace.projects[0]=project;
 const prepared=prepareIncrementalWorkspace(workspace,base,encodeDerived(project.working.weave.derived)),loaded=unpackWorkspace(prepared.packed);validateTrustedWorkspace(loaded);assert.deepEqual(loaded,workspace);
 const broken=clone(loaded);broken.projects[0].carrierStudies[0].revisions.pop();broken.projects[0].carrierStudies[0].latestRevisionId=broken.projects[0].carrierStudies[0].revisions.at(-1).id;
 assert.throws(()=>validateTrustedWorkspace(broken),/missing revision/);const recovered=recoverCarrierAncestry(broken);assert.equal(recovered.count,1);assert.deepEqual(recovered.workspace,workspace);assert.equal(broken.projects[0].carrierStudies[0].revisions.length,1);
 const conflicting=clone(broken);conflicting.projects[0].working.weave.sourceContext.snapshot.carrier.families.A.spacing++;assert.throws(()=>recoverCarrierAncestry(conflicting),/Conflicting/);
 const incomplete=clone(broken);incomplete.projects[0].working.weave.sourceContext.snapshot.parentRevisionId='missing';incomplete.projects[0].weaveStudies=[];assert.throws(()=>recoverCarrierAncestry(incomplete),/incomplete/);
});
test('ancestry recovery uses retained transaction snapshots for missing intermediate revisions',()=>{
 let {workspace,project}=pattern();project=saveCarrierStudy(project,'PATTERN').project;project=createWeaveStudy(project,project.working.carrierSourceRevisionId);project=addInfluence(project);const original=clone(project.carrierStudies);
 project.working.carrier.families.A.spacing+=1;let saved=saveCarrierStudy(project,'PATTERN');project=retargetWeaveSource(saved.project,saved.revisionId);project.working=refreshWeave(project.working,project.id);const history=[{projects:[clone(project)]}];
 project.working.carrier.families.A.spacing+=1;saved=saveCarrierStudy(project,'PATTERN');project=retargetWeaveSource(saved.project,saved.revisionId);project.working=refreshWeave(project.working,project.id);workspace.projects[0]=project;const expected=clone(workspace);workspace.projects[0].carrierStudies=original;
 assert.throws(()=>recoverCarrierAncestry(workspace),/incomplete/);assert.deepEqual(recoverCarrierAncestry(workspace,history).workspace,expected);
});
