import test from 'node:test';import assert from 'node:assert/strict';import {Worker} from 'node:worker_threads';
import {square,validateBoundary} from '../dist/boundary.mjs';import {createRectangularCarrier} from '../dist/carrier.mjs';
import {createWorkspace,saveCarrierStudy,createWeaveStudy,addAttractor,candidateAttractor,saveWeaveStudy,validateTrustedWorkspace,clone} from '../dist/document.mjs';
import {deriveAttractor,deformPoint,nextUp,nextDown,ATTRACTOR_VERSIONS} from '../dist/attractor.mjs';import {digest,canonical} from '../dist/weave.mjs';
import {LocalStore,STORE_KEY,SCHEMA4_RECOVERY_KEY} from '../dist/storage.mjs';
import {decodeDerived} from '../dist/storage-codec.mjs';
function setup(boundary=square(),spacing=50){const w=createWorkspace(),p=w.projects[0];p.working.boundary=boundary;p.working.carrier=createRectangularCarrier('carrier-r1b');p.working.carrier.families.A.spacing=spacing;p.working.carrier.families.B.spacing=spacing;w.projects[0]=saveCarrierStudy(p,'SOURCE').project;w.projects[0]=createWeaveStudy(w.projects[0],w.projects[0].carrierStudies[0].latestRevisionId);w.projects[0]=addAttractor(w.projects[0]);return w;}
const derive=p=>deriveAttractor(p.working.boundary,p.working.carrier,p.id,p.working.weave.sourceContext,p.working.weave.generation,digest);
test('schema-4 raw recovery is write-once before current schema-6 persistence',()=>{const legacy=createWorkspace();legacy.schemaVersion=4;const raw=JSON.stringify(legacy),map=new Map([[STORE_KEY,raw]]),memory={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)},store=new LocalStore(memory),loaded=store.load();store.save(loaded);assert.equal(map.get(SCHEMA4_RECOVERY_KEY),raw);assert.equal(JSON.parse(map.get(STORE_KEY)).schemaVersion,6);loaded.projects[0].name='SECOND SAVE';store.save(loaded);assert.equal(map.get(SCHEMA4_RECOVERY_KEY),raw);assert.equal(JSON.parse(map.get(STORE_KEY)).projects[0].name,'SECOND SAVE');});
test('approved attractor equation and tension fixtures are exact',()=>{const g={version:'single-attractor-v1',tension:0,attractor:{id:'f',kind:'attractor',center:{x:0,y:0},radius:100,strength:50,enabled:true,falloffVersion:'smooth-local-v1'}};assert.deepEqual(deformPoint({x:0,y:50},g),{x:0,y:41.5625});g.tension=50;assert.deepEqual(deformPoint({x:0,y:50},g),{x:0,y:45.25390625});g.tension=100;assert.deepEqual(deformPoint({x:17,y:50},g),{x:17,y:50});g.tension=0;g.attractor.strength=0;assert.deepEqual(deformPoint({x:17,y:50},g),{x:17,y:50});});
test('nextUp/down enclose finite values, zeros and infinities',()=>{for(const x of [-Number.MAX_VALUE,-1,-Number.MIN_VALUE,-0,0,Number.MIN_VALUE,1,Number.MAX_VALUE]){assert.ok(nextDown(x)<=x);assert.ok(nextUp(x)>=x);assert.ok(nextDown(x)<nextUp(x));}assert.equal(nextUp(Infinity),Infinity);assert.equal(nextDown(-Infinity),-Infinity);});
test('certified geometry meets epsilon and includes an incoming outside source',()=>{const w=setup(square(),20),p=w.projects[0];p.working.weave.generation.attractor={...p.working.weave.generation.attractor,center:{x:240,y:0},radius:100,strength:100};const d=derive(p);assert.ok(d.diagnostics.maxCertifiedError<=d.diagnostics.epsilon);assert.equal(d.diagnostics.accuracyScope,'unclipped-curve-to-polyline');const incoming=d.strands.find(s=>s.family==='B'&&s.k===-13);assert.ok(incoming);assert.ok(incoming.fragments.flatMap(f=>f.points).some(q=>q.x<250));assert.ok(d.diagnostics.segments<=65536&&d.diagnostics.edgeTests<=8000000);});
test('concave clipping retains separated fragments and monotone source parameters',()=>{const u=validateBoundary([{x:-150,y:-150},{x:150,y:-150},{x:150,y:150},{x:50,y:150},{x:50,y:-50},{x:-50,y:-50},{x:-50,y:150},{x:-150,y:150}]),w=setup(u),p=w.projects[0],d=derive(p);assert.ok(d.strands.some(s=>s.fragments.length>1));for(const s of d.strands)for(const f of s.fragments){assert.ok(f.t1>f.t0);assert.equal(f.points.length-1,f.segmentErrorBounds.length);assert.ok(f.segmentErrorBounds.every(e=>e<=d.diagnostics.epsilon));}});
test('schema 5 supports mixed immutable v1/v2 revisions and trusted complete commit',()=>{const w=setup(),p=w.projects[0];p.working.weave.derived=derive(p);validateTrustedWorkspace(w);let saved=saveWeaveStudy(p,'FIELD').project;assert.equal(saved.weaveStudies[0].revisions[0].weaveVersion,ATTRACTOR_VERSIONS.study);const first=clone(saved.weaveStudies[0].revisions[0]);saved=candidateAttractor(saved,{attractor:{center:{x:20,y:0}}});saved.working.weave.derived=derive(saved);saved=saveWeaveStudy(saved,'FIELD').project;assert.deepEqual(saved.weaveStudies[0].revisions[0],first);assert.equal(saved.weaveStudies[0].revisions.length,2);});
test('dense synchronous evaluator remains a recorded diagnostic',()=>{const pts=[];for(let i=0;i<100;i++){const a=i*2*Math.PI/100,r=i%2?250:220;pts.push({x:r*Math.cos(a),y:r*Math.sin(a)})}const w=setup(validateBoundary(pts),2.5),p=w.projects[0];for(let i=0;i<3;i++)derive(p);const times=[];let result;for(let i=0;i<30;i++){const s=performance.now();result=derive(p);times.push(performance.now()-s)}times.sort((a,b)=>a-b);const report={executionPath:'synchronous-main-process-diagnostic',governsAcceptance:false,runs:30,p50:times[15],p95:times[28],max:times[29],comparison:{persistentWorkerP95Ms:375,persistentWorkerMaximumMs:400,p95WithinWorkerThreshold:times[28]<=375,maximumWithinWorkerThreshold:times[29]<=400}};console.log('R1B certified synchronous evaluator diagnostic',JSON.stringify(report));assert.equal(result.complete,true);assert.ok(result.diagnostics.maxCertifiedError<=result.diagnostics.epsilon);});
test('versioned worker echoes identity and one exact transferable certified payload',async()=>{const w=setup(),p=w.projects[0],candidate={boundary:p.working.boundary,carrier:p.working.carrier,sourceContext:p.working.weave.sourceContext,generation:p.working.weave.generation},input=digest(candidate),message={protocolVersion:ATTRACTOR_VERSIONS.protocol,workerBuildId:'TEST',sessionId:'session',requestSequence:7,requestId:'session:7',boardId:p.id,weaveStudyId:p.working.weave.studyId,baseCommittedFingerprint:'base',candidateInputFingerprint:input,algorithmVersions:{...ATTRACTOR_VERSIONS},candidate};const worker=new Worker(new URL('../scripts/r1b-worker-node.mjs',import.meta.url)),result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('worker timeout')),750);worker.once('message',m=>{clearTimeout(timer);resolve(m)});worker.once('error',reject);worker.postMessage(message)});await worker.terminate();assert.equal(result.type,'success');for(const key of ['requestId','requestSequence','sessionId','boardId','weaveStudyId','baseCommittedFingerprint','candidateInputFingerprint'])assert.equal(result[key],message[key]);assert.equal(result.result.complete,true);assert.equal(result.resultCanonicalFingerprint,result.payload.id);assert.deepEqual(decodeDerived(result.payload),result.result);assert.ok(result.timing.deriveMs>=0&&result.timing.encodeMs>=0);});
test('worker failures retain request identity and a typed error code',async()=>{const worker=new Worker(new URL('../scripts/r1b-worker-node.mjs',import.meta.url)),result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('worker timeout')),750);worker.once('message',m=>{clearTimeout(timer);resolve(m)});worker.once('error',reject);worker.postMessage({protocolVersion:ATTRACTOR_VERSIONS.protocol,requestSequence:9,requestId:'session:9'})});await worker.terminate();assert.equal(result.type,'failure');assert.equal(result.requestId,'session:9');assert.equal(result.requestSequence,9);assert.equal(result.error.code,'invalid-request');assert.match(result.error.message,/Unsupported worker request/);});
