import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,saveCarrierStudy,createWeaveStudy,addInfluence,candidateVariation,saveWeaveStudy,serializeWorkspace,parseBackup,validateTrustedWorkspace} from '../dist/document.mjs';
import {createRectangularCarrier} from '../dist/carrier.mjs';
import {packWorkspace,unpackWorkspace} from '../dist/storage-codec.mjs';
import {refreshWeave} from '../dist/weave.mjs';

test('a stochastic weave record keeps the seed that generated it',()=>{
 const ws=createWorkspace();
 let project=ws.projects[0];
 project.working.carrier=createRectangularCarrier();
 project=saveCarrierStudy(project,'WEAVE A',{generatorVersion:'TEST-BUILD'}).project;
 assert.equal(project.carrierStudies[0].revisions[0].generation.seed,null);
 project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);
 project=addInfluence(project);
 project=candidateVariation(project,{seed:4242,family:'A',amount:40});
 project.working=refreshWeave(project.working,project.id);
 const before=project.carrierStudies[0].revisions.length;
 project=saveWeaveStudy(project,'FIELD',true).project;
 const revisions=project.carrierStudies[0].revisions;
 assert.equal(revisions.length,before+1);
 assert.equal(revisions[0].generation.seed,null);
 assert.equal(revisions.at(-1).generation.seed,4242);
 assert.equal(revisions.at(-1).generation.parameters.variation.families.A.amount,40);
 project.working.weave.generation.variation.seed=1;
 assert.equal(revisions.at(-1).generation.seed,4242);
 project=candidateVariation(project,{seed:99});
 project.working=refreshWeave(project.working,project.id);
 project=saveWeaveStudy(project,'FIELD',true).project;
 const saved=project.carrierStudies[0].revisions;
 assert.equal(saved[0].generation.seed,null);
 assert.equal(saved[1].generation.seed,4242);
 assert.equal(saved.at(-1).generation.seed,99);
 const count=saved.length;
 project=saveWeaveStudy(project,'FIELD',true).project;
 assert.equal(project.carrierStudies[0].revisions.length,count);
 assert.equal(project.carrierStudies[0].revisions.at(-1).generation.seed,99);
 ws.projects[0]=project;
 validateTrustedWorkspace(ws);
 const reloaded=unpackWorkspace(packWorkspace(parseBackup(serializeWorkspace(ws))));
 assert.equal(reloaded.projects[0].carrierStudies[0].revisions.at(-1).generation.seed,99);
 assert.equal(reloaded.projects[0].carrierStudies[0].revisions[1].generation.seed,4242);
});
