import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,finalizeSavedWeaveRecord,saveCarrierStudy,serializeWorkspace,parseBackup,createWeaveStudy,addInfluence,saveWeaveStudy} from '../dist/document.mjs';
import {createRectangularCarrier} from '../dist/carrier.mjs';
import {packWorkspace,unpackWorkspace} from '../dist/storage-codec.mjs';
import {refreshWeave} from '../dist/weave.mjs';
import {resolveAnalysisGeometry,separateStoredGeometry} from '../dist/weave-record.mjs';

test('regeneration keeps the stored geometry as the evaluation target',()=>{
 const ws=createWorkspace();
 let project=ws.projects[0];
 project.working.carrier=createRectangularCarrier();
 project=finalizeSavedWeaveRecord(project,'WEAVE A',{generatorVersion:'TEST-BUILD'}).project;
 const entry=project.carrierStudies[0];
 const pinned=entry.revisions[0];
 const snapshot=resolveAnalysisGeometry(project,pinned);
 const fingerprint=pinned.geometryRef.geometryFingerprint;
 ws.projects[0]=project;
 const reloaded=unpackWorkspace(packWorkspace(parseBackup(serializeWorkspace(ws))));
 const restoredProject=reloaded.projects[0];
 const restored=restoredProject.carrierStudies[0].revisions[0];
 const before=structuredClone(restored);
 const report=separateStoredGeometry(restoredProject,restored);
 assert.equal(report.evaluationTarget,'stored');
 assert.equal(report.mismatch,false);
 assert.equal(report.storedRecoverable,true);
 assert.equal(report.geometryFingerprint,fingerprint);
 assert.deepEqual(restored,before);
 assert.deepEqual(resolveAnalysisGeometry(restoredProject,restored),snapshot);
 const edited=structuredClone(restored);
 edited.generation.parameters.families.A.spacing=12;
 const diverged=separateStoredGeometry(restoredProject,edited);
 assert.equal(diverged.mismatch,true);
 assert.equal(diverged.evaluationTarget,'stored');
 assert.match(diverged.reason,/preserved/);
 assert.equal(edited.geometryRef.geometryFingerprint,fingerprint);
 assert.deepEqual(resolveAnalysisGeometry(restoredProject,edited),snapshot);
 restoredProject.working.carrier.families.A.spacing=12;
 const resaved=finalizeSavedWeaveRecord(restoredProject,'WEAVE A',{generatorVersion:'TEST-BUILD'}).project;
 const record=resaved.carrierStudies[0];
 assert.equal(record.revisions[0].geometryRef.geometryFingerprint,fingerprint);
 assert.notEqual(record.revisions.at(-1).geometryRef.geometryFingerprint,fingerprint);
 assert.equal(record.generatorRevisionId,record.revisions.at(-1).id);
 assert.deepEqual(resolveAnalysisGeometry(resaved,record.revisions[0]),snapshot);
 const current=separateStoredGeometry(resaved,record.revisions.at(-1));
 assert.equal(current.evaluationTarget,'stored');
 assert.equal(current.mismatch,false);
 assert.notEqual(current.geometryFingerprint,fingerprint);
});

test('a regenerated field result does not replace the pinned centerlines',()=>{
 const ws=createWorkspace();
 let project=ws.projects[0];
 project.working.carrier=createRectangularCarrier();
 project=saveCarrierStudy(project,'WEAVE',{generatorVersion:'TEST-BUILD'}).project;
 project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);
 project=addInfluence(project);
 project.working=refreshWeave(project.working,project.id);
 project=saveWeaveStudy(project,'FIELD',true).project;
 const revision=project.carrierStudies[0].revisions.at(-1);
 const snapshot=resolveAnalysisGeometry(project,revision);
 const stored=structuredClone(revision.geometryRef);
 const report=separateStoredGeometry(project,revision);
 assert.equal(report.mismatch,true);
 assert.equal(report.evaluationTarget,'stored');
 assert.equal(report.storedRecoverable,true);
 assert.match(report.reason,/preserved/);
 assert.deepEqual(revision.geometryRef,stored);
 assert.deepEqual(resolveAnalysisGeometry(project,revision),snapshot);
});
