import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,saveCarrierStudy,serializeWorkspace,parseBackup,validateTrustedWorkspace} from '../dist/document.mjs';
import {createRectangularCarrier} from '../dist/carrier.mjs';
import {packWorkspace,unpackWorkspace} from '../dist/storage-codec.mjs';
import {appendAnalysisRun,appendEvaluationRun,createAnalysisRun,createEvaluationRun,createLineageRecord,CRITERION_IDS} from '../dist/weave-record.mjs';

const FIRST='2026-09-26T12:00:00.000Z',LATER='2026-09-26T13:00:00.000Z';

test('saved weaves keep empty future containers through save and load',()=>{
 const ws=createWorkspace();
 let project=ws.projects[0];
 project.working.carrier=createRectangularCarrier();
 project=saveCarrierStudy(project,'WEAVE A',{now:FIRST,generatorVersion:'TEST-BUILD'}).project;
 const entry=project.carrierStudies[0];
 assert.deepEqual(entry.derivedAnalysis,{});
 assert.deepEqual(entry.evaluations,[]);
 assert.deepEqual(entry.designerData,{});
 assert.deepEqual(entry.lineage,{});
 entry.evaluations.push({id:'kept'});
 project.working.carrier.families.A.spacing=80;
 project=saveCarrierStudy(project,'WEAVE A',{now:LATER,generatorVersion:'TEST-BUILD'}).project;
 assert.deepEqual(project.carrierStudies[0].evaluations,[{id:'kept'}]);
 assert.deepEqual(project.carrierStudies[0].derivedAnalysis,{});
 assert.deepEqual(project.carrierStudies[0].designerData,{});
 assert.deepEqual(project.carrierStudies[0].lineage,{});
 ws.projects[0]=project;
 validateTrustedWorkspace(ws);
 const reloaded=unpackWorkspace(packWorkspace(parseBackup(serializeWorkspace(ws))));
 assert.deepEqual(reloaded.projects[0].carrierStudies[0].evaluations,[{id:'kept'}]);
 assert.deepEqual(reloaded.projects[0].carrierStudies[0].derivedAnalysis,{});
 delete reloaded.projects[0].carrierStudies[0].derivedAnalysis;
 delete reloaded.projects[0].carrierStudies[0].evaluations;
 delete reloaded.projects[0].carrierStudies[0].designerData;
 delete reloaded.projects[0].carrierStudies[0].lineage;
 assert.doesNotThrow(()=>validateTrustedWorkspace(reloaded));
 reloaded.projects[0].carrierStudies[0].evaluations={};
 assert.throws(()=>validateTrustedWorkspace(reloaded),/Invalid weave record containers/);
});

test('versioned analysis, evaluation, and lineage survive save and reload without replacing an older record',()=>{
 const ws=createWorkspace();
 let project=ws.projects[0];
 project.working.carrier=createRectangularCarrier();
 project=saveCarrierStudy(project,'WEAVE A',{now:FIRST,generatorVersion:'TEST-BUILD'}).project;
 const entry=project.carrierStudies[0];
 const artifact={artifactId:'artifact-map-1',version:'modulation-map-v1',weaveId:entry.weaveId,geometryFingerprint:'geometry-fingerprint-1',analysisRunId:'analysis-1'};
 const first=createAnalysisRun({analysisRunId:'analysis-1',geometryFingerprint:'geometry-fingerprint-1',status:'analyzed',moduleVersions:{modulation:'modulation-v1'},outputs:{coverage:0.5},artifacts:[artifact],warnings:['PARTIAL GRID']});
 appendAnalysisRun(entry,first);
 const prior=structuredClone(entry.derivedAnalysis);
 appendAnalysisRun(entry,createAnalysisRun({analysisRunId:'analysis-2',geometryFingerprint:'geometry-fingerprint-2',status:'analysis-failed',moduleVersions:{events:'events-v1'},warnings:['NO EVENTS']}));
 assert.deepEqual(prior.runs[0],first);
 assert.equal(entry.derivedAnalysis.runs.length,2);
 const criterionResults=Object.fromEntries(CRITERION_IDS.map(id=>[id,{criterionId:id,status:id==='WV-05'?'not-applicable':'not-evaluated',normalizedScore:null,rating:null,components:{},safeguards:{},evidenceRefs:id==='WV-02'?[artifact]:[],criterionLogicVersion:'logic-v1',calibrationVersion:'calibration-v1',warnings:[]}]));
 appendEvaluationRun(entry,createEvaluationRun({evaluationId:'evaluation-1',analysisRunId:'analysis-1',createdAt:LATER,status:'partial',criterionResults,versions:{logic:'logic-v1',calibration:'calibration-v1'}}));
 entry.lineage=createLineageRecord({parent:{weaveId:'weave-parent',revisionId:'carrier-revision-parent'},downstream:[{objectId:'interpreter-1',kind:'package'}],handoffs:[{handoffId:'handoff-1',createdAt:LATER,artifactId:'artifact-map-1'}]});
 entry.designerData={note:'KEEP'};
 project.working.carrier.families.A.spacing=70;
 project=saveCarrierStudy(project,'WEAVE A',{now:LATER,generatorVersion:'TEST-BUILD'}).project;
 ws.projects[0]=project;
 validateTrustedWorkspace(ws);
 const stored=structuredClone(project.carrierStudies[0]);
 const reloaded=unpackWorkspace(packWorkspace(parseBackup(serializeWorkspace(ws)))).projects[0].carrierStudies[0];
 assert.deepEqual(reloaded.derivedAnalysis,stored.derivedAnalysis);
 assert.deepEqual(reloaded.evaluations,stored.evaluations);
 assert.deepEqual(reloaded.lineage,stored.lineage);
 assert.deepEqual(reloaded.designerData,{note:'KEEP'});
 assert.equal(reloaded.evaluations[0].criterionResults['WV-01'].normalizedScore,null);
 assert.equal(reloaded.evaluations[0].history.length,0);
 assert.equal(reloaded.derivedAnalysis.runs[0].analysisRunId,'analysis-1');
 delete project.carrierStudies[0].derivedAnalysis;
 delete project.carrierStudies[0].evaluations;
 delete project.carrierStudies[0].designerData;
 delete project.carrierStudies[0].lineage;
 ws.projects[0]=project;
 assert.doesNotThrow(()=>validateTrustedWorkspace(ws));
 assert.throws(()=>createAnalysisRun({analysisRunId:'analysis-3',geometryFingerprint:'geometry-fingerprint-1',status:'analyzed',artifacts:[{...artifact,points:[{x:0,y:0}]}]}),/reference/);
});
