import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,saveCarrierStudy,createWeaveStudy,addInfluence,candidateVariation,duplicateLibraryItem,serializeWorkspace,parseBackup,validateTrustedWorkspace} from '../dist/document.mjs';
import {createRectangularCarrier} from '../dist/carrier.mjs';
import {createStitchSource} from '../dist/stitch-source.mjs';
import {packWorkspace,unpackWorkspace} from '../dist/storage-codec.mjs';
import {refreshWeave} from '../dist/weave.mjs';

const FIRST='2026-09-26T12:00:00.000Z',LATER='2026-09-26T13:00:00.000Z';

test('each saved weave keeps the generator state from the moment it was saved',()=>{
 const ws=createWorkspace();
 let project=ws.projects[0];
 project.working.carrier=createRectangularCarrier();
 project.working.carrier.families.A.spacing=40;
 project.working.carrier.angleDegrees=12;
 project=saveCarrierStudy(project,'WEAVE A',{now:FIRST,generatorVersion:'TEST-BUILD'}).project;
 const first=project.carrierStudies[0].revisions[0].generation;
 assert.equal(first.parameters.families.A.spacing,40);
 assert.equal(first.parameters.families.B.spacing,50);
 assert.equal(first.parameters.angleDegrees,12);
 assert.equal(first.settings.generatorVersion,'rect-v1');
 assert.equal(first.modes.kind,'rectangular');
 assert.equal(first.seed,null);
 assert.equal(first.domain.closed,true);
 assert.equal(first.domain.points.length,4);
 project=createWeaveStudy(project,project.carrierStudies[0].latestRevisionId);
 project=addInfluence(project);
 project=candidateVariation(project,{seed:2222});
 project.working.carrier.families.A.spacing=70;
 project=saveCarrierStudy(project,'WEAVE A',{now:LATER,generatorVersion:'TEST-BUILD'}).project;
 const revisions=project.carrierStudies[0].revisions;
 assert.equal(revisions[0].generation.parameters.families.A.spacing,40);
 assert.equal(revisions[0].generation.seed,null);
 assert.equal(revisions[1].generation.parameters.families.A.spacing,70);
 assert.equal(revisions[1].generation.seed,2222);
 assert.equal(revisions[1].generation.parameters.variation.families.A.amount,0);
 const domainX=revisions[1].generation.domain.points[0].x;
 project.working.carrier.families.A.spacing=11;
 project.working.carrier.angleDegrees=90;
 project.working.boundary.points[0].x=12345;
 assert.equal(revisions[0].generation.parameters.families.A.spacing,40);
 assert.equal(revisions[1].generation.parameters.families.A.spacing,70);
 assert.equal(revisions[1].generation.parameters.angleDegrees,12);
 assert.equal(revisions[1].generation.domain.points[0].x,domainX);
 project.working.boundary.points[0].x=domainX;
 project.working.carrier.families.A.spacing=80;
 project.working.carrier.angleDegrees=-20;
 const both=saveCarrierStudy(project,'WEAVE B',{now:LATER,generatorVersion:'TEST-BUILD'}).project;
 assert.equal(both.carrierStudies[0].revisions[0].generation.parameters.families.A.spacing,40);
 assert.equal(both.carrierStudies[1].revisions[0].generation.parameters.families.A.spacing,80);
 assert.equal(both.carrierStudies[1].revisions[0].generation.parameters.angleDegrees,-20);
 both.working.carrier.families.A.spacing=3;
 assert.equal(both.carrierStudies[0].revisions[1].generation.parameters.families.A.spacing,70);
 assert.equal(both.carrierStudies[1].revisions[0].generation.parameters.families.A.spacing,80);
 assert.notEqual(both.working.carrier.families.A,both.carrierStudies[1].revisions[0].generation.parameters.families.A);
 both.working.carrier.families.A.spacing=80;
 both.working.carrier.angleDegrees=-20;
 both.working=refreshWeave(both.working,both.id);
 ws.projects[0]=both;
 validateTrustedWorkspace(ws);
 const reloaded=parseBackup(serializeWorkspace(ws));
 assert.equal(reloaded.projects[0].carrierStudies[0].revisions[0].generation.parameters.families.A.spacing,40);
 assert.equal(unpackWorkspace(packWorkspace(reloaded)).projects[0].carrierStudies[1].revisions[0].generation.parameters.families.A.spacing,80);
 const copied=duplicateLibraryItem(reloaded.projects[0],'pattern',reloaded.projects[0].carrierStudies[1].id);
 assert.equal(copied.carrierStudies[2].revisions[0].generation.parameters.families.A.spacing,80);
 copied.carrierStudies[2].revisions[0].generation.parameters.families.A.spacing=1;
 assert.equal(copied.carrierStudies[1].revisions[0].generation.parameters.families.A.spacing,80);
});

test('stitch controls are copied into the saved generator snapshot',()=>{
 const ws=createWorkspace();
 let project=ws.projects[0];
 project.working.carrier=createStitchSource('herringbone-square','stitch-a',2);
 project.working.carrier.parameters.width=100;
 project.working.carrier.parameters.rotation=15;
 project=saveCarrierStudy(project,'STITCH A',{now:FIRST,generatorVersion:'TEST-BUILD'}).project;
 delete project.working.familyCatalog;
 project.working.carrier=createStitchSource('double-herringbone-field','stitch-b',2);
 project.working.carrier.parameters.rowStep=.7;
 project.working.carrier.parameters.pitch=140;
 project=saveCarrierStudy(project,'STITCH B',{now:LATER,generatorVersion:'TEST-BUILD'}).project;
 const a=project.carrierStudies[0].revisions[0].generation,b=project.carrierStudies[1].revisions[0].generation;
 assert.equal(a.parameters.width,100);
 assert.equal(a.parameters.rotation,15);
 assert.equal(a.modes.recipeId,'herringbone-square');
 assert.equal(a.seed,null);
 assert.equal(b.parameters.rowStep,.7);
 assert.equal(b.parameters.pitch,140);
 assert.equal(b.modes.recipeId,'double-herringbone-field');
 assert.equal(b.modes.crossRowPolicy,'unresolved');
 project.working.carrier.parameters.pitch=10;
 assert.equal(a.parameters.width,100);
 assert.equal(b.parameters.pitch,140);
 project.working.carrier.parameters.pitch=140;
 ws.projects[0]=project;
 validateTrustedWorkspace(ws);
});
