import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,finalizeSavedWeaveRecord,saveCarrierStudy} from '../dist/document.mjs';
import {createRectangularCarrier} from '../dist/carrier.mjs';
import {applyGeneratorSnapshot} from '../dist/weave-record.mjs';
import {canonical} from '../dist/weave.mjs';

test('Open in Generator restores the saved controls and leaves that record unchanged',()=>{
 const ws=createWorkspace();
 const project=ws.projects[0];
 project.working.carrier=createRectangularCarrier();
 const saved=finalizeSavedWeaveRecord(project,'WEAVE A',{now:'2026-09-26T12:00:00.000Z',generatorVersion:'TEST-BUILD'});
 const entry=saved.project.carrierStudies[0];
 const pinned=entry.revisions[0];
 const before=canonical(pinned.generation);
 assert.equal(entry.generatorRevisionId,pinned.id);
 const edited=structuredClone(saved.project);
 edited.working.carrier.families.A.spacing=90;
 edited.working.carrier.families.A.angleDegrees=33;
 edited.working.carrier.families.A.offset=12;
 edited.working.carrier.families.A.density=70;
 const autosaved=saveCarrierStudy(edited,'WEAVE A',{now:'2026-09-26T12:05:00.000Z',generatorVersion:'TEST-BUILD'});
 const record=autosaved.project.carrierStudies[0];
 assert.equal(record.revisions.length,2);
 assert.equal(record.generatorRevisionId,pinned.id);
 assert.equal(autosaved.project.working.carrier.families.A.spacing,90);
 assert.equal(canonical(record.revisions[0].generation),before);
 const restored=applyGeneratorSnapshot(autosaved.project.working,record.revisions[0].generation);
 assert.equal(restored.carrier.families.A.spacing,pinned.generation.parameters.families.A.spacing);
 assert.equal(restored.carrier.families.A.angleDegrees,pinned.generation.parameters.families.A.angleDegrees);
 assert.equal(restored.carrier.families.A.offset,0);
 assert.equal(restored.carrier.families.A.density,100);
 assert.equal(restored.carrier.kind,pinned.generation.modes.kind);
 assert.equal(restored.boundary.closed,pinned.generation.domain.closed);
 assert.deepEqual(restored.boundary.points,pinned.generation.domain.points);
 assert.equal(autosaved.project.working.carrier.families.A.spacing,90);
 assert.equal(record.revisions.length,2);
 assert.equal(canonical(record.revisions[0].generation),before);
 const seeded=structuredClone(restored);
 seeded.weave={generation:{variation:{seed:9,families:{A:{amount:1}}}}};
 const generation=structuredClone(pinned.generation);
 generation.seed=4242;
 generation.parameters.variation={families:{A:{amount:40}}};
 const withSeed=applyGeneratorSnapshot(seeded,generation);
 assert.equal(withSeed.weave.generation.variation.seed,4242);
 assert.equal(withSeed.weave.generation.variation.families.A.amount,40);
 assert.equal(seeded.weave.generation.variation.seed,9);
 assert.equal(generation.seed,4242);
 const mismatch=structuredClone(generation);
 mismatch.modes={kind:'stitch-recipe-v1'};
 assert.throws(()=>applyGeneratorSnapshot(restored,mismatch),/Saved generator mode does not match this weave/);
});
