import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,finalizeSavedWeaveRecord,validateTrustedWorkspace} from '../dist/document.mjs';
import {createRectangularCarrier} from '../dist/carrier.mjs';
import {clearAnalysisCache} from '../dist/analysis.mjs';
import {evaluateWeave} from '../dist/evaluation.mjs';
import {influenceCoverage,scoreWV01} from '../dist/wv01.mjs';

const near=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-12,`${actual} is not ${expected}`);
const family=(id,presence,retainedStrandCount=10)=>({familyId:id,presence,retainedStrandCount});
const pair=(angle,spacingRatio,densityDifference=0)=>({familyA:'A',familyB:'B',angleDifference:angle,spacingRatio,densityDifference});

test('duplicate, uncoupled, coupled, and low-presence fields follow the WV-01 handoff',()=>{
 const duplicate=scoreWV01({families:[family('A',1),family('B',1)],pairs:[pair(0,1)]});
 near(duplicate.familyDistinctness,0);
 near(duplicate.relationalCoupling,1);
 near(duplicate.normalized,0);
 assert.equal(duplicate.rating,1);
 const uncoupled=scoreWV01({families:[family('A',1),family('B',1)],pairs:[pair(0,2)]});
 near(uncoupled.familyDistinctness,.21/.85);
 near(uncoupled.relationalCoupling,0);
 near(uncoupled.normalized,0);
 assert.equal(uncoupled.rating,1);
 assert.equal(uncoupled.pairs[0].parallel,0);
 const coupled=scoreWV01({families:[family('A',1),family('B',1)],pairs:[pair(90,1)]});
 const distinctness=.5/.85;
 near(coupled.familyDistinctness,distinctness);
 near(coupled.relationalCoupling,1);
 near(coupled.normalized,Math.sqrt(distinctness));
 assert.equal(coupled.rating,Math.round((1+4*Math.sqrt(distinctness))*10)/10);
 assert.ok(coupled.rating>uncoupled.rating);
 assert.ok(coupled.rating>duplicate.rating);
 const low=scoreWV01({families:[family('A',1,20),family('B',7/66,2)],pairs:[pair(90,1)]});
 assert.equal(low.presenceCap,.7);
 near(low.base,Math.sqrt(distinctness));
 near(low.normalized,.7);
 assert.ok(low.normalized<low.base);
 assert.equal(low.rating,3.8);
 const same=scoreWV01({families:[family('A',1),family('B',1)],pairs:[pair(90,1)],influences:[{enabled:true,coverage:1,strengths:{A:50,B:50}}]});
 const split=scoreWV01({families:[family('A',1),family('B',1)],pairs:[pair(90,1)],influences:[{enabled:true,coverage:1,strengths:{A:80,B:20}}]});
 near(split.familyDistinctness,.65);
 near(split.pairs[0].shared,1);
 assert.ok(split.base>same.base);
 assert.equal(scoreWV01({families:[family('A',1,4)],pairs:[]}).status,'not-applicable');
});

test('a saved orthogonal weave stores WV-01 evidence without an overall score',()=>{
 clearAnalysisCache();
 const ws=createWorkspace();
 let project=ws.projects[0];
 project.working.carrier=createRectangularCarrier();
 project=finalizeSavedWeaveRecord(project,'WEAVE A',{now:'2026-09-27T12:00:00.000Z',generatorVersion:'TEST-BUILD'}).project;
 const entry=project.carrierStudies[0];
 const result=evaluateWeave(project,entry,{evaluationId:'evaluation-wv01',createdAt:'2026-09-27T12:10:00.000Z'});
 const scored=result.evaluation.criterionResults['WV-01'];
 const distinctness=scored.components.familyDistinctness,coupling=scored.components.relationalCoupling,cap=scored.safeguards.effectiveFamilyPresence;
 assert.equal(scored.status,'evaluated');
 near(scored.normalizedScore,Math.min(Math.sqrt(distinctness*coupling),cap));
 assert.equal(scored.rating,Math.round((1+4*scored.normalizedScore)*10)/10);
 assert.equal(scored.evidenceRefs.length,3);
 assert.equal(result.evaluation.criterionResults['WV-02'].status,'evaluated');
 assert.equal(result.evaluation.criterionResults['WV-03'].status,'evaluated');
 assert.equal(result.evaluation.criterionResults['WV-04'].status,'evaluated');
 assert.equal(result.evaluation.criterionResults['WV-05'].status,'evaluated');
 assert.equal(Object.hasOwn(result.evaluation,'overallScore'),false);
 assert.equal(scored.submetrics.pairs.length>0,true);
 assert.equal(scored.explanation.includes('WV-01 scored'),true);
 const boundary=[{x:-100,y:-100},{x:100,y:-100},{x:100,y:100},{x:-100,y:100}];
 near(influenceCoverage(boundary,{x:0,y:0},1000),1);
 assert.ok(influenceCoverage(boundary,{x:0,y:0},10)<.05);
 ws.projects[0]=project;
 validateTrustedWorkspace(ws);
});
