const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const dir=path.resolve('verification/local-r1b');fs.mkdirSync(dir,{recursive:true});
const failurePath=path.join(dir,'browser-failure-latest.json');
 let browser,page,stage='launch',iteration=null,trace=[],phaseDiagnostics=[],documentEpoch='initial';
const writeJson=(file,value)=>fs.writeFileSync(path.join(dir,file),JSON.stringify(value,null,2));
(async()=>{
 browser=await chromium.launch({executablePath:process.env.BROWSER_EXE||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1500,height:1000},acceptDownloads:true});page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await context.addInitScript(()=>{window.__long=[];window.__inspection=[];window.__inspectRead=(label='full-workspace read')=>{const start=performance.now();try{return window.readTool.execute({})}finally{window.__inspection.push({label,start,end:performance.now()})}};new PerformanceObserver(l=>window.__long.push(...l.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});Object.defineProperty(document,'modelContext',{configurable:true,value:{registerTool:t=>window.readTool=t}})});
 await page.goto('http://127.0.0.1:43830/');await page.waitForFunction(()=>window.readTool);
 const read=(label='full-workspace read')=>page.evaluate(label=>window.__inspectRead(label),label);
 const snapshot=async()=>({status:await page.locator('#status').innerText(),statusError:await page.locator('#status').evaluate(e=>e.classList.contains('error')),model:await read('terminal snapshot')});
 const open=async id=>{if(!await page.locator(id).evaluate(e=>e.open))await page.locator(id+'>summary').click()};
 const initialState=await read('initial state'),legacyRaw=JSON.stringify(initialState.workspace);assert.equal(initialState.build,'WF-R1B-DELTA-20260916');assert.equal(initialState.storage.version,'weave-idb-v1');assert.equal(initialState.storage.generation,1);
 const runCycle=async(label,action,index=null)=>{
   stage=label;iteration=index;const before=(await read('runCycle pre-action state')).workerTelemetry.sequence;await action();
   try{await page.waitForFunction(previous=>{const events=window.__inspectRead('runCycle terminal poll').workerTelemetry.events;return events.some(e=>e.seq>previous&&(e.type==='committed'||e.type==='failed'));},before,{timeout:1100});}
   catch(error){const snap=await snapshot();throw Object.assign(Error(`No terminal worker event for ${label} after request sequence ${before}; status=${snap.status}`),{cause:error,snapshot:snap});}
   const snap=await snapshot(),events=snap.model.workerTelemetry.events,terminal=events.filter(e=>e.seq>before&&(e.type==='committed'||e.type==='failed')).at(-1),dispatched=events.find(e=>e.type==='dispatched'&&e.seq===terminal.seq);
   const record={label,iteration,documentEpoch,requestSequence:terminal.seq,requestId:terminal.requestId,requestStarted:dispatched?.requestStarted??null,committedAt:terminal.at??null,type:terminal.type,code:terminal.code||null,message:terminal.message||null,workerMs:terminal.workerMs??null,totalMs:terminal.totalMs,phases:terminal.phases||null,status:snap.status,statusError:snap.statusError};trace.push(record);
   console.log('R1B cycle',JSON.stringify(record));
   if(terminal.type==='failed')throw Object.assign(Error(`Worker ${terminal.code} at ${label}${index===null?'':` iteration ${index}`}: ${terminal.message}`),{snapshot:snap,terminal});
   const q=terminal.phases;assert.ok(q&&Object.values(q).every(Number.isFinite),`missing phase telemetry at ${label}`);const diagnosticLimits={dispatchMs:100,deriveMs:325,encodeMs:125,transferMs:100,validationMs:40,admissionMs:30,transactionMs:100,historyMs:5};for(const [phase,limit] of Object.entries(diagnosticLimits))if(q[phase]>limit)phaseDiagnostics.push({label,iteration,requestSequence:terminal.seq,phase,valueMs:q[phase],diagnosticTargetMs:limit});assert.ok(terminal.workerMs<=400,`worker ${terminal.workerMs}`);assert.ok(q.renderMs<=50,`render ${q.renderMs}`);
   assert.ok(terminal.totalMs<=750,`750 ms completion maximum exceeded at ${label}: ${JSON.stringify(record)}`);
   return terminal;
 };
 stage='fixture setup';await open('#carrier-section');await page.locator('#create-carrier').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('CARRIER CREATED'),null,{timeout:3000});await page.locator('#carrier-name').fill('SOURCE');await page.locator('#save-carrier').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('CARRIER STUDY REVISION SAVED'),null,{timeout:3000});await open('#weave-section');const rev=(await read()).workspace.projects[0].carrierStudies[0].latestRevisionId;await page.locator('#weave-source-revision').selectOption(rev);await page.locator('#create-weave').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('WEAVE CREATED'),null,{timeout:3000});
 await page.evaluate(()=>{window.__pendingLatency=null;let clicked=0;document.querySelector('#add-attractor').addEventListener('click',()=>clicked=performance.now(),{capture:true});new MutationObserver(()=>{if(clicked&&document.querySelector('#status').textContent.includes('CALCULATING')&&window.__pendingLatency===null)window.__pendingLatency=performance.now()-clicked}).observe(document.querySelector('#status'),{childList:true,subtree:true})});
 const cold=await runCycle('cold add attractor',()=>page.locator('#add-attractor').click());await page.waitForFunction(()=>window.__pendingLatency!==null);const pendingMs=await page.evaluate(()=>window.__pendingLatency);assert.ok(pendingMs<=50,'pending '+pendingMs);assert.equal(await page.locator('#save-weave').isEnabled(),true);
 await page.locator('#show-weave-derived').check();
 let state=await read(),w=state.workspace.projects[0].working.weave;assert.equal(w.weaveVersion,'weave-study-v2');assert.equal(w.derived.complete,true);assert.ok(w.derived.diagnostics.maxCertifiedError<=w.derived.diagnostics.epsilon);
 await runCycle('coalesced numeric edit',async()=>{await page.locator('#attractor-x').fill('10');await page.locator('#attractor-x').fill('20');await page.locator('#attractor-x').fill('30');await page.locator('#attractor-x').press('Tab')});assert.equal((await read()).workspace.projects[0].working.weave.generation.attractor.center.x,30);
 stage='pending undo cancellation';await page.locator('#attractor-x').fill('70');await page.waitForFunction(()=>window.__inspectRead('pending cancellation poll').workerTelemetry.pending!==null);await page.locator('#undo').click();assert.equal((await read('pending cancellation result')).workspace.projects[0].working.weave.generation.attractor.center.x,30);
 const details=page.locator('details').filter({has:page.locator('#coordinates')});await details.locator('summary').click();const pts=[];for(let i=0;i<100;i++){const a=i*2*Math.PI/100,r=i%2?250:220;pts.push(`${r*Math.cos(a)},${r*Math.sin(a)}`)}await runCycle('dense boundary',async()=>{await page.locator('#coordinates').fill(pts.join('\n'));await page.locator('#apply-coordinates').click()});
 for(const id of ['#a-spacing','#b-spacing'])await runCycle(`dense spacing ${id}`,async()=>{await page.locator(id).fill('2.5');await page.locator(id).press('Tab')});
 const derivedDom=await page.evaluate(()=>{const state=window.__inspectRead('derived DOM parity'),strands=state.workspace.projects[0].working.weave.derived.strands,expected={};for(const family of ['A','B']){const selected=strands.filter(s=>s.family===family),fragments=selected.reduce((n,s)=>n+s.fragments.length,0),segments=selected.reduce((n,s)=>n+s.fragments.reduce((m,f)=>m+f.points.length-1,0),0);expected[family]={fragments,segments};}return{children:[...document.querySelector('#weave-derived-layer').children].map(node=>({tag:node.tagName,family:node.dataset.weaveFamily,className:node.getAttribute('class'),fragments:Number(node.dataset.fragments),segments:Number(node.dataset.segments),moves:(node.getAttribute('d').match(/M/g)||[]).length,lines:(node.getAttribute('d').match(/L/g)||[]).length})),expected};});assert.ok(derivedDom.children.length<=2,JSON.stringify(derivedDom));for(const child of derivedDom.children){assert.equal(child.tag,'path');assert.match(child.className,new RegExp(`family-${child.family.toLowerCase()}`));assert.equal(child.fragments,derivedDom.expected[child.family].fragments);assert.equal(child.segments,derivedDom.expected[child.family].segments);assert.equal(child.moves,child.fragments);assert.equal(child.lines,child.segments);}
 const totals=[],worker=[];for(let i=0;i<30;i++){if(i===0)await page.evaluate(()=>{const ids=['board-list','geometry','source-lattice-layer','family-a-layer','family-b-layer','weave-source-layer'],telemetry=window.__inspectRead('stable DOM baseline').renderTelemetry;window.__r1bStable={nodes:Object.fromEntries(ids.map(id=>[id,[...document.getElementById(id).childNodes]])),full:telemetry.full,targeted:telemetry.targeted};});const terminal=await runCycle('dense worker loop',async()=>{await page.locator('#attractor-x').fill(String(i%2));await page.locator('#attractor-x').press('Tab')},i);if(i===0){const stable=await page.evaluate(()=>{const before=window.__r1bStable,ids=Object.keys(before.nodes),telemetry=window.__inspectRead('stable DOM comparison').renderTelemetry;return{same:ids.every(id=>{const now=[...document.getElementById(id).childNodes],prior=before.nodes[id];return now.length===prior.length&&now.every((node,index)=>node===prior[index]);}),fullBefore:before.full,fullAfter:telemetry.full,targetedBefore:before.targeted,targetedAfter:telemetry.targeted};});assert.equal(stable.same,true,JSON.stringify(stable));assert.equal(stable.fullAfter,stable.fullBefore,JSON.stringify(stable));assert.ok(stable.targetedAfter>stable.targetedBefore,JSON.stringify(stable));}totals.push(terminal.totalMs);worker.push(terminal.workerMs)}
 totals.sort((a,b)=>a-b);worker.sort((a,b)=>a-b);const timings={pendingMs,coldTotalMs:cold.totalMs,workerP95:worker[28],workerMax:worker[29],completeP95:totals[28],completeMax:totals[29]};state=await read();assert.ok(state.workspace.projects[0].working.weave.derived.diagnostics.segments>30000);
 const beforeReloadTelemetry=await page.evaluate(()=>({longTasks:window.__long,inspections:window.__inspection}));stage='schema 5 save and reload';await page.locator('#weave-name').fill('R1B FIELD');await page.locator('#save-weave').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('REVISION SAVED'),null,{timeout:3000});await page.reload();await page.waitForFunction(()=>window.readTool&&document.querySelector('#status').textContent.includes('WORKSPACE RESTORED'),null,{timeout:3000});documentEpoch='restored';state=await read('restored state');assert.equal(state.workspace.projects[0].weaveStudies[0].revisions.length,1);assert.equal(state.workspace.projects[0].working.weave.derived.complete,true);assert.ok(state.storage.previousRoot);const storageFacts=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('weave-foundation-v1');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}),tx=db.transaction(['heads','snapshots','payloads','records'],'readonly'),get=(s,k)=>new Promise((resolve,reject)=>{const r=tx.objectStore(s).get(k);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}),head=await get('heads','main'),current=await get('snapshots',head.currentRoot),previous=await get('snapshots',head.previousRoot);return{generation:head.generation,migrationComplete:head.migrationComplete,current:!!current,previous:!!previous,payloads:current.payloadIds.length,records:current.recordIds.length}});assert.equal(storageFacts.migrationComplete,true);assert.equal(storageFacts.current,true);assert.equal(storageFacts.previous,true);assert.ok(storageFacts.payloads>=1);
 stage='multi-tab generation conflict';const stalePage=await context.newPage();await stalePage.goto('http://127.0.0.1:43830/');await stalePage.waitForFunction(()=>window.readTool&&document.querySelector('#status').textContent.includes('WORKSPACE RESTORED'),null,{timeout:5000});const staleX=(await stalePage.evaluate(()=>window.__inspectRead('stale tab initial state'))).workspace.projects[0].working.weave.generation.attractor.center.x;await page.bringToFront();await open('#weave-section');await runCycle('authoritative tab edit',async()=>{await page.locator('#attractor-x').fill('2');await page.locator('#attractor-x').press('Tab')});await stalePage.bringToFront();if(!await stalePage.locator('#weave-section').evaluate(e=>e.open))await stalePage.locator('#weave-section>summary').click();await stalePage.locator('#attractor-x').fill('3');await stalePage.locator('#attractor-x').press('Tab');await stalePage.waitForFunction(()=>document.querySelector('#status').textContent.includes('CONCURRENT-CHANGE'),null,{timeout:1500});const staleState=await stalePage.evaluate(()=>window.__inspectRead('stale tab rejected state'));assert.equal(staleState.workspace.projects[0].working.weave.generation.attractor.center.x,staleX);assert.equal((await read('authoritative tab final state')).workspace.projects[0].working.weave.generation.attractor.center.x,2);await stalePage.close();await page.bringToFront();
 stage='portable backup';const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#backup').click()]),backup=fs.readFileSync(await download.path(),'utf8'),backupEnvelope=JSON.parse(backup);assert.equal(backupEnvelope.version,2);assert.ok(Buffer.byteLength(backup)<=10*1024*1024);
 stage='portable import';const importContext=await browser.newContext({viewport:{width:1200,height:800}});await importContext.addInitScript(()=>Object.defineProperty(document,'modelContext',{configurable:true,value:{registerTool:t=>window.readTool=t}}));const imported=await importContext.newPage();await imported.goto('http://127.0.0.1:43830/');await imported.waitForFunction(()=>window.readTool);await imported.locator('#import-backup').click();await imported.locator('#backup-json').fill(backup);await imported.locator('#confirm-import').click();await imported.waitForFunction(()=>document.querySelector('#status').textContent.includes('BACKUP IMPORTED'),null,{timeout:5000});const importedState=await imported.evaluate(()=>window.readTool.execute({}));assert.ok(importedState.workspace.projects.some(p=>p.weaveStudies.some(s=>s.revisions.length===1)));await importContext.close();
 stage='legacy migration';const migrationContext=await browser.newContext({viewport:{width:1200,height:800}});await migrationContext.addInitScript(raw=>{localStorage.setItem('weave-foundation-workspace-v2',raw);Object.defineProperty(document,'modelContext',{configurable:true,value:{registerTool:t=>window.readTool=t}})},legacyRaw);const migrated=await migrationContext.newPage();await migrated.goto('http://127.0.0.1:43830/');await migrated.waitForFunction(()=>window.readTool&&document.querySelector('#status').textContent.includes('WORKSPACE RESTORED'),null,{timeout:5000});const migrationFacts=await migrated.evaluate(async raw=>{const unchanged=localStorage.getItem('weave-foundation-workspace-v2')===raw,db=await new Promise((resolve,reject)=>{const r=indexedDB.open('weave-foundation-v1');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}),tx=db.transaction(['heads','recovery'],'readonly'),get=(s,k)=>new Promise((resolve,reject)=>{const r=tx.objectStore(s).get(k);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}),head=await get('heads','main'),recovery=await get('recovery','weave-foundation-workspace-v2');return{unchanged,migrationComplete:head.migrationComplete,recoveryExact:recovery.value===raw}},legacyRaw);assert.deepEqual(migrationFacts,{unchanged:true,migrationComplete:true,recoveryExact:true});await migrationContext.close();
 await open('#weave-section');await page.screenshot({path:path.join(dir,'dense-field.png'),fullPage:true});const afterReloadTelemetry=await page.evaluate(()=>({longTasks:window.__long,inspections:window.__inspection})),longs=beforeReloadTelemetry.longTasks.map(x=>({...x,documentEpoch:'initial'})).concat(afterReloadTelemetry.longTasks.map(x=>({...x,documentEpoch:'restored'}))),inspectionIntervals=beforeReloadTelemetry.inspections.map(x=>({...x,documentEpoch:'initial'})).concat(afterReloadTelemetry.inspections.map(x=>({...x,documentEpoch:'restored'}))),applicationInteractionWindows=trace.filter(x=>Number.isFinite(x.requestStarted)&&Number.isFinite(x.committedAt)).map(x=>({label:x.label,iteration:x.iteration,documentEpoch:x.documentEpoch,start:x.requestStarted,end:x.committedAt})),overlaps=(a,b)=>a.documentEpoch===b.documentEpoch&&a.start<a.end&&a.start+a.duration>b.start,verifierLongTasks=longs.filter(task=>inspectionIntervals.some(interval=>overlaps(task,interval))),applicationLongTasks=longs.filter(task=>applicationInteractionWindows.some(interval=>overlaps(task,interval))&&!inspectionIntervals.some(interval=>overlaps(task,interval))),unclassifiedLongTasks=longs.filter(task=>!verifierLongTasks.includes(task)&&!applicationLongTasks.includes(task));assert.deepEqual(errors,[]);assert.equal(applicationLongTasks.length,0,JSON.stringify(applicationLongTasks));stage='final aggregate performance';assert.ok(timings.coldTotalMs<=200,JSON.stringify(timings));assert.ok(timings.workerP95<=375,JSON.stringify(timings));assert.ok(timings.workerMax<=400,JSON.stringify(timings));assert.ok(timings.completeP95<=650,JSON.stringify(timings));assert.ok(timings.completeMax<=750,JSON.stringify(timings));
 writeJson('browser-results.json',{build:'WF-R1B-DELTA-20260916',passed:['pending display','worker commit','coalescing/stale rejection','pending undo cancellation','dense certified completion','transactional current/previous reload','multi-tab stale generation rejection','portable v2 export/import','legacy exact-byte migration','phase telemetry recorded','application-attributable long-task classification'],timings,storageFacts,backupBytes:Buffer.byteLength(backup),phaseDiagnostics,longTasks:longs,verifierInspectionIntervals:inspectionIntervals,applicationInteractionWindows,verifierLongTasks,applicationLongTasks,unclassifiedLongTasks,errors,cycles:trace});await browser.close();browser=null;console.log('PASS local browser R1B',JSON.stringify({...timings,diagnosticPhaseMisses:phaseDiagnostics.length,applicationLongTasks:applicationLongTasks.length,backupBytes:Buffer.byteLength(backup)}));
 })().catch(async error=>{let final=null;try{if(page)final={status:await page.locator('#status').innerText(),statusError:await page.locator('#status').evaluate(e=>e.classList.contains('error')),model:await page.evaluate(()=>window.readTool?.execute({})||null)}}catch{}const evidence={build:'WF-R1B-DELTA-20260916',passed:false,stage,iteration,error:{name:error.name,message:error.message,stack:error.stack},terminal:error.terminal||null,finalStatus:final?.status||null,finalStatusError:final?.statusError??null,pendingWorker:final?.model?.workerTelemetry?.pending||null,activeWorker:final?.model?.workerTelemetry?.active||null,workerEvents:final?.model?.workerTelemetry?.events||[],phaseDiagnostics,cycles:trace};fs.writeFileSync(failurePath,JSON.stringify(evidence,null,2));console.error('R1B browser failure evidence',failurePath);console.error(JSON.stringify({stage,iteration,finalStatus:evidence.finalStatus,terminal:evidence.terminal},null,2));console.error(error);if(browser)await browser.close();process.exitCode=1});
